---
name: Terraform Provider Cache Example

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_PLUGIN_CACHE_DIR: $HOME/.terraform.d/plugin-cache

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15

      - name: Configure Terraform Plugin Cache
        run: |
          mkdir -p "$TF_PLUGIN_CACHE_DIR"

          cat > ~/.terraformrc <<EOF
          plugin_cache_dir = "$TF_PLUGIN_CACHE_DIR"
          EOF

          echo "=== Terraform RC ==="
          cat ~/.terraformrc

          echo "=== Cache Dir ==="
          ls -la "$TF_PLUGIN_CACHE_DIR"

      - name: Cache Terraform Providers
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::388458311239:role/github-action-role

      - name: Terraform Init
        run: terraform init -no-color